project_name: wfi
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: dx-oss
    name: wfi
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}-{{.Version}}"  
dockers:
- goos: linux
  goarch: amd64
  goarm: ''
  binaries:
  - "{{.ProjectName}}"
  image_templates:
  - "dxdx/{{.ProjectName}}:latest"
  - "dxdx/{{.ProjectName}}:{{ .Tag }}"
  - "dxdx/{{.ProjectName}}:v{{ .Major }}"
  - "ghcr.io/dx-oss/{{.ProjectName}}:latest"
  - "ghcr.io/dx-oss/{{.ProjectName}}:{{ .Tag }}"
  - "ghcr.io/dx-oss/{{.ProjectName}}:v{{ .Major }}"  
  dockerfile: Dockerfile
  build_flag_templates:
  - "--label=org.label-schema.schema-version=1.0"
  - "--label=org.label-schema.version={{.Version}}"
  - "--label=org.label-schema.name={{.ProjectName}}"
