project_name: wfi
builds:
  - id: 'wfi'
    binary: 'wfi'
    env:
      - CGO_ENABLED=0
      - VERSION={{ .Version }}
    ldflags:
      - -s -w -X main.build={{.Version}}
    goos: 
      - linux
    goarch:
      - amd64
      - arm
      - arm64      
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: dxcn
    name: wfi
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}-{{.Version}}"
dockers:
- id: wfi
  ids:
  - wfi
  use: buildx
  image_templates:
  - "dxdx/{{.ProjectName}}:latest"
  - "dxdx/{{.ProjectName}}:{{ .Tag }}"
  - "dxdx/{{.ProjectName}}:v{{ .Major }}"     
  build_flag_templates:
  - "--label=org.label-schema.schema-version=1.0"
  - "--label=org.label-schema.version={{.Version}}"
  - "--label=org.label-schema.name={{.ProjectName}}"